server:
  port: 8084

spring:
  application:
    name: CART

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8088/eureka
  instance:
    prefer-ip-address: true
    instance-id: CART:8084  # 고정 값으로 설정
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  resources:
    static-locations: classpath:/static/